module MyColors

export BLACK, PITCH_DARK, WHITE, OFFWHITE,
    RED, DARK_RED, LIGHT_RED, RED_TINT, PURE_RED,
    GREEN, DARK_GREEN, LIGHT_GREEN, GREEN_TINT, PEACOCK_GREEN,
    BLUE, DARK_BLUE, LIGHT_BLUE, BLUE_TINT, OCEAN_BLUE,
    ORANGE, LIGHT_ORANGE, YELLOW, LIGHT_YELLOW, GOLD,
    PINK, LAVENDER, VIOLET, CYAN, BROWN, CHOCOLATE, ALL_COLORS, SAT_COLORS, UNSAT_COLORS, BASE_COLORS

const BLACK = "#20262e"
const PITCH_DARK = "#1a2028"

const WHITE = "#f2faff"
const OFFWHITE = "#d8e9e6"

const RED = "#f03e50"
const DARK_RED = "#d83034"
const LIGHT_RED = "#ff5a5f"
const RED_TINT = "#f2baaf"
const PURE_RED = "#dd2c2f"

const GREEN = "#52b788"
const DARK_GREEN = "#37867e"
const LIGHT_GREEN = "#95d5b2"
const GREEN_TINT = "#d8f3dc"
const PEACOCK_GREEN = "#1d4f5f"

const BLUE = "#0496ff"
const DARK_BLUE = "#283d53"
const LIGHT_BLUE = "#28b2f7"
const BLUE_TINT = "#90e0ef"
const OCEAN_BLUE = "#05668d"

const ORANGE = "#f46036"
const LIGHT_ORANGE = "#e9724c"

const YELLOW = "#ffc857"
const LIGHT_YELLOW = "#ffd97d"
const GOLD = "#f1a226"

const PINK = "#ff87ab"
const LAVENDER = "#c8b6ff"
const VIOLET = const PURPLE = "#8b2fc9"

const CYAN = "#68d8d6"
const BROWN = const CHOCOLATE = "#9d6b53"

const ALL_COLORS = [BLACK, PITCH_DARK, WHITE, OFFWHITE,
    RED, DARK_RED, LIGHT_RED, RED_TINT, PURE_RED,
    GREEN, DARK_GREEN, LIGHT_GREEN, GREEN_TINT, PEACOCK_GREEN,
    BLUE, DARK_BLUE, LIGHT_BLUE, BLUE_TINT, OCEAN_BLUE,
    ORANGE, LIGHT_ORANGE, YELLOW, LIGHT_YELLOW, GOLD,
    PINK, LAVENDER, VIOLET, CYAN, BROWN, CHOCOLATE]

const SAT_COLORS = [OFFWHITE, RED, DARK_RED, LIGHT_RED, RED_TINT, PURE_RED,
    GREEN, DARK_GREEN, LIGHT_GREEN, GREEN_TINT, PEACOCK_GREEN,
    BLUE, DARK_BLUE, LIGHT_BLUE, BLUE_TINT, OCEAN_BLUE,
    ORANGE, LIGHT_ORANGE, YELLOW, LIGHT_YELLOW, GOLD,
    PINK, LAVENDER, VIOLET, CYAN, BROWN, CHOCOLATE]

const UNSAT_COLORS = [BLACK, PITCH_DARK, WHITE]

const BASE_COLORS = [RED, DARK_RED, LIGHT_RED, RED_TINT, PURE_RED,
    GREEN, DARK_GREEN, LIGHT_GREEN, GREEN_TINT, PEACOCK_GREEN,
    BLUE, DARK_BLUE, LIGHT_BLUE, BLUE_TINT, OCEAN_BLUE]

end  # module MyColors